defaultBaseImage: distroless.dev/alpine-base:latest
builds:
  - id: bindl
    dir: ./cmd/bindl
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X
      - main.version={{.Env.VERSION}}
      - -X
      - main.boxed=y
