name: Bindl

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: bindl-dev/bindl@main

    - uses: actions/checkout@v2

    - run: bindl sync

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "bindl sync"
