name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
        - unit
        - integration
        - functional
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Test
      run: go version && make test/${{ matrix.tests }}

  license:
    runs-on: ubuntu-latest
    steps:
    - uses: bindl-dev/bindl@main

    - uses: actions/checkout@v2

    - name: Add license headers
      run: make license

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "make license"

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: bindl-dev/bindl@main

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: golangci-lint
      run: make lint/gh-actions

  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: gofmt
      run: go version && gofmt -w $(find . -name '*.go')

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "gofmt -w"

  gomod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: go mod tidy
      run: go version && go mod tidy

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "go mod tidy"
