name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
        - unit
        - integration
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Test
      run: go version && make test/${{ matrix.tests }}
